---
# Source: trino/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trino
  labels:
    helm.sh/chart: trino-0.1.0
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: trino/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: trino
  labels:
    helm.sh/chart: trino-0.1.0
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
---
# Source: trino/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino
  labels:
    helm.sh/chart: trino-0.1.0
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: trino
      app.kubernetes.io/instance: trino
  template:
    metadata:
      labels:
        helm.sh/chart: trino-0.1.0
        app.kubernetes.io/name: trino
        app.kubernetes.io/instance: trino
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: trino
      securityContext:
        {}
      containers:
        - name: trino
          securityContext:
            {}
          image: "docker.io/trinodb/trino:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
# Source: trino/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "trino-test-connection"
  labels:
    helm.sh/chart: trino-0.1.0
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['trino:8080']
  restartPolicy: Never
